Repository hnyjzj/jdy-client, pull requests merged in 2024-10, with the labels that each got.

#13 build(github): add release-drafter action
  .github/workflows/release-drafter.yml
Labels: configuration

#3 feat: 新增成品列表相关页面
  assets/icons/down.svg
  assets/icons/example.svg
  assets/icons/projection.svg
  assets/images/empty.svg
  components/common/Empty.vue
  components/common/Step.vue
  components/common/Tags.vue
  components/common/button/Rounded.vue
  components/common/button/Square.vue
  components/common/header/Gradient.vue
  components/common/header/Theme.vue
  components/common/tab/Secondary.vue
  components/goods/finished/Entry.vue
  components/goods/finished/List.vue
  components/goods/finished/Stocktaking.vue
  package.json
  pages/goods/finished/list.vue
  pages/goods/finished/stocktaking.vue
  pages/goods/finished/warehouse.vue
  pages/goods/index.vue
  pnpm-lock.yaml
  types/goods.d.ts
  uno.config.ts
Labels: enhancement

#17 feat: use nuxt/icon
  assets/icons/test666.svg
  nuxt.config.ts
  package.json
  pages/index/index.vue
  pnpm-lock.yaml
Labels: enhancement

#16 feat: 登录和个人中心页面
  components/my/user/option.vue
  components/my/user/userinfo.vue
  pages/login/index.vue
  pages/my/user/index.vue
Labels: enhancement

#18 ci: 发布声明排除依赖机器人
  .github/release-drafter.yml
Labels: configuration

#19 refactor: 只修改了图片路径 和 图片引用
  assets/icons/down.svg
  assets/icons/example.svg
  assets/icons/moon-fill.svg
  assets/icons/moon-white.svg
  assets/icons/product-money.svg
  assets/icons/product-neworder.svg
  assets/icons/product-newuser.svg
  assets/icons/product-selected.svg
  assets/icons/product-target.svg
  assets/icons/product-toggle.svg
  assets/icons/projection.svg
  assets/icons/sun-blue.svg
  assets/icons/sun-line.svg
  assets/icons/test666.svg
  assets/image/home/homeIcon.svg
  assets/image/work/could.svg
  components/common/Dark.vue
  components/product/home/Card.vue
  components/product/home/Sort.vue
  components/product/manage/Fold.vue
  components/work/card/Digitalization.vue
  layouts/default.vue
  nuxt.config.ts
  pages/index/index.vue
  pages/login/index.vue
  pages/product/manage/home.vue
  pages/work/table/todos.vue
  public/background/bg.png
  public/background/menu-bg.svg
  public/images/background/bg.png
  public/images/background/darkbg.png
  public/images/banner/product.png
  public/images/banner/work.png
  public/images/empty.svg
Labels: maintenance

#23 fix: 更改路径和文件名
  assets/icons/crosspath.svg
  assets/icons/scanit.svg
  assets/icons/search.svg
  components/common/Frame.vue
  components/common/Model.vue
  components/common/Popup.vue
  components/common/button/Bottom.vue
  components/sale/info/Card.vue
  pages/sale/order.vue
  public/images/model/title1.png
  public/images/model/title2.png
  public/images/sale/bag.png
Labels: bugfix

#26 ci: 发布声明排除依赖机器人
  .github/release-drafter.yml
Labels: configuration

#24 refactor: 使用colorMode 替代 usedark
  components/common/Dark.vue
  composables/useDark.ts
  layouts/default.vue
  nuxt.config.ts
  package.json
  pages/work/table/todos.vue
  pnpm-lock.yaml
Labels: maintenance

#25 feat: 新增销售单页面
  components/common/Frame.vue
  components/sale/add/Base.vue
  components/sale/add/Card.vue
  components/sale/add/Product.vue
  components/sale/add/Settlement.vue
  pages/sale/sales/add.vue
  pages/sale/sales/order.vue
  uno.config.ts
Labels: enhancement

#27 docs: 统一文件目录命名
  assets/icons/check-box.svg
  assets/icons/down.svg
  assets/icons/level_diamond.svg
  components/product/finished/Entry.vue
  components/product/finished/List.vue
  components/product/finished/Stocktaking.vue
  pages/goods/index.vue
  pages/product/finished/list.vue
  pages/product/finished/stocktaking.vue
  pages/product/finished/warehouse.vue
Labels: documentation

#30 style: 编辑按钮
  assets/icons/moon-white.svg
  assets/icons/moon.svg
  assets/icons/sun-line.svg
  assets/icons/sun.svg
  components/common/button/Irregular.vue
  components/common/dark/Index.vue
  components/common/tabbar/Index.vue
  components/product/manage/Card.vue
  components/product/manage/Company.vue
  layouts/default.vue
  nuxt.config.ts
  pages/index/index.vue
  pages/product/manage/goods.vue
  pages/product/manage/list.vue
  pages/work/table/index.vue
  uno.config.ts
Labels: maintenance

#31 feat: 修改部分页面同步设计图
  assets/icons/table-not.svg
  assets/icons/table-select.svg
  assets/icons/todo-not.svg
  assets/icons/todo-select.svg
  assets/icons/userinfo-not.svg
  assets/icons/userinfo-select.svg
  components/common/dark/Index.vue
  components/common/tabbar/Index.vue
  components/work/card/Action.vue
  components/work/card/Digitalization.vue
  components/work/card/Information.vue
  components/work/card/greet.vue
  layouts/table.vue
  pages/login/index.vue
  pages/my/user/index.vue
  pages/product/manage/goods.vue
  pages/product/manage/list.vue
  pages/work/table/index.vue
  pages/work/table/todos.vue
  utils/getTime.ts
Labels: enhancement

#40 feat: 添加跳转链接
  .editorconfig
  assets/icons/my-profile.svg
  assets/icons/my-question.svg
  assets/icons/my-setting.svg
  components/common/coll/Index.vue
  components/login/info.vue
  components/login/tips.vue
  components/my/user/Option.vue
  components/my/user/Userinfo.vue
  components/work/card/Enter.vue
  layouts/default.vue
  pages/index/index.vue
  pages/login/index.vue
  pages/my/user/index.vue
  pages/work/table/index.vue
Labels: enhancement

#38 feat: 会员页面开发
  components/common/model/Index.vue
  components/customer/member/Level.vue
  layouts/member.vue
  pages/customer/member/billing.vue
  pages/customer/member/card.vue
  pages/customer/member/equity.vue
  pages/customer/member/level.vue
Labels: enhancement

#42 feat: 封装fetch和修改icon
  .gitignore
  .vscode/settings.json
  app.vue
  assets/css/main.scss
  components/common/coll/Index.vue
  components/common/dark/Index.vue
  components/common/tabbar/Index.vue
  components/icon/Index.vue
  components/my/user/Option.vue
  components/product/filter/Filter.vue
  components/product/filter/Search.vue
  components/product/home/Sort.vue
  components/product/manage/Bottom.vue
  components/product/manage/Card.vue
  components/product/manage/Company.vue
  components/work/card/Action.vue
  components/work/card/Digitalization.vue
  components/work/card/Information.vue
  nuxt.config.ts
  package.json
  pages/index/index.vue
  pages/my/user/index.vue
  pages/product/manage/list.vue
  pages/work/table/index.vue
  pnpm-lock.yaml
  renovate.json
  stores/user.ts
  uno.config.ts
  utils/fetch.ts
Labels: enhancement

#49 feat: 引入echarts
  assets/icons/drop-down.svg
  components/customer/data/Chart.vue
  components/customer/data/Sumup.vue
  components/customer/data/Tabel.vue
  components/customer/data/Transcript.vue
  components/customer/data/nav.vue
  components/summary/stock/Chart.vue
  components/summary/stock/List.vue
  components/summary/stock/Total.vue
  nuxt.config.ts
  package.json
  pages/customer/data/ranking.vue
  pages/summary/stock/detail.vue
  pages/summary/stock/index.vue
  pnpm-lock.yaml
  public/images/summary/stock.png
  public/images/top/top1.svg
  public/images/top/top2.svg
  public/images/top/top3.svg
  renovate.json
Labels: enhancement

#59 deps: Update dependency ubuntu to latest
  .github/workflows/check.yml
  .github/workflows/label-prs.yml
  .github/workflows/release-drafter.yml
Labels: configuration
