Repository hnyjzj/jdy-client, pull requests merged in 2025-07, with the labels that each got.

#171 feat: 新增系统默认模板的打印选择
  components/print/Board.vue
  components/print/lists/List.vue
  pages/sale/sales/order.vue
  pages/system/print/edit/index.vue
  pages/system/print/new/index.vue
  public/images/print/printtemp.png
Labels: enhancement

#172 feat: 修改新增销售单
  components/sale/add/Depositorder.vue
  components/sale/add/parts/Search.vue
  components/sale/deposit/List.vue
  pages/sale/deposit/add.vue
  pages/sale/deposit/list.vue
  pages/sale/other/add.vue
  pages/sale/other/list.vue
  pages/sale/sales/add.vue
  pages/sale/sales/list.vue
  pages/sale/service/add.vue
  pages/sale/service/list.vue
Labels: enhancement

#173 feat: 选中权限使用树形穿梭框
  components/authority/api.vue
  components/authority/fun.vue
  pages/product/accessorie/allocate/info.vue
  pages/product/check/add.vue
  pages/product/check/index.vue
  pages/system/authority/index.vue
Labels: enhancement

#175 feat: 修改订单管理
  components/common/confirm/Pay.vue
  components/sale/deposit/Details.vue
  components/sale/deposit/List.vue
  components/sale/order/Detail.vue
  components/sale/other/Info.vue
  components/sale/sales/List.vue
  components/sale/service/add/Base.vue
  components/sale/service/info/Index.vue
  components/sale/service/list/Index.vue
  components/staff/manage/Card.vue
  pages/login/loading.vue
  pages/sale/deposit/list.vue
  pages/sale/deposit/order.vue
  pages/sale/other/info.vue
  pages/sale/sales/order.vue
  pages/sale/service/add.vue
  pages/sale/service/info.vue
  types/depositOrders.d.ts
  types/repair.d.ts
Labels: enhancement

#174 feat: 成品检索&上传图片抽离
  components/accessorie/warehouse/accessorie.vue
  components/accessorie/warehouse/category.vue
  components/auth/verify.vue
  components/authority/fun.vue
  components/authority/transfer.vue
  components/common/loading/index.vue
  components/home/Store.vue
  components/product/allocate/base.vue
  components/product/check/warehouse.vue
  components/product/filter/Search.vue
  composables/useIdentity.ts
  pages/product/accessorie/category/index.vue
  pages/product/accessorie/enter/info.vue
  pages/product/allocate/add.vue
  pages/product/allocate/index.vue
  pages/product/allocate/info.vue
  pages/product/check/add.vue
  pages/product/check/info.vue
  pages/product/list/uploadimg.vue
  pages/product/list/view.vue
  pages/product/manage/edit.vue
  pages/product/manage/finished/info.vue
  pages/product/warehouse/index.vue
  pages/product/warehouse/info.vue
  pages/system/authority/index.vue
  pages/work/table/index.vue
  stores/check.ts
  stores/fininshed.ts
  stores/finishedEnter.ts
  types/allocate.d.ts
  types/check.d.ts
  types/finished.d.ts
  types/finishedEnter.d.ts
  types/user.d.ts
Labels: enhancement

#177 feat: 修改销售单
  components/sale/add/Member.vue
  components/sale/add/Product.vue
  components/sale/add/product/List.vue
  components/sale/add/product/Popup.vue
Labels: enhancement

#176 feat: 盘点人可多选&增加删除盘点产品功能
  components/product/upload/Choose.vue
  pages/product/check/add.vue
  pages/product/check/index.vue
  pages/product/check/info.vue
  stores/check.ts
  types/check.d.ts
Labels: enhancement

#179 chore: 修改打印模板中主销人的字段
  components/print/Board.vue
  pages/sale/sales/order.vue
  stores/fininshed.ts
Labels: maintenance

#182 chore: 完善会员搜索功能，优化部分表现样式
  components/common/page/Index.vue
  components/member/lists/List.vue
  pages/member/lists/list.vue
Labels: maintenance

#180 feat: 修改销售单列表显示
  components/sale/add/Base.vue
  components/sale/add/Settlement.vue
  components/sale/deposit/Balance.vue
  components/sale/deposit/Staff.vue
  components/sale/other/AddBase.vue
  components/sale/other/Balance.vue
  components/sale/sales/List.vue
  components/sale/service/add/Balance.vue
  components/sale/service/add/Base.vue
  components/staff/manage/Stores.vue
  pages/manage/staffs/staff/list.vue
Labels: enhancement

#183 feat: 修改了分配员工时点击默认显示第一页数据
  components/region/AssignStaff.vue
  components/region/Assignstore.vue
  components/stores/AssignStaff.vue
  stores/authority.ts
  types/staff.d.ts
Labels: enhancement

#184 feat: 新增选择常用语功能
  components/product/manage/Company.vue
  components/sale/add/Settlement.vue
  components/sale/deposit/Balance.vue
  components/sale/deposit/Details.vue
  components/sale/order/Detail.vue
  components/sale/other/Info.vue
  pages/sale/deposit/add.vue
  pages/sale/other/info.vue
  pages/sale/sales/add.vue
  pages/system/phrase/index.vue
  stores/phrase.ts
  types/depositOrders.d.ts
  types/order.d.ts
  types/phrase.d.ts
Labels: enhancement

#188 feat: 修改不能使用负数提交
  components/sale/add/Settlement.vue
  components/sale/deposit/Balance.vue
  components/sale/other/Balance.vue
  components/sale/service/add/Balance.vue
  pages/sale/deposit/add.vue
  pages/sale/other/add.vue
  pages/sale/sales/add.vue
  pages/sale/service/add.vue
  types/order.d.ts
Labels: enhancement

#185 fix: 入库单切换门店更新
  components/accessorie/enter/base.vue
  components/correspond/store.vue
  components/product/allocate/base.vue
  components/product/filter/Filter.vue
  components/product/manage/Company.vue
  pages/product/accessorie/allocate/info.vue
  pages/product/accessorie/category/index.vue
  pages/product/accessorie/enter/index.vue
  pages/product/accessorie/list.vue
  pages/product/allocate/add.vue
  pages/product/allocate/info.vue
  pages/product/list/finished.vue
  pages/product/list/old.vue
  pages/product/warehouse/index.vue
  pages/system/authority/index.vue
  stores/authority.ts
Labels: bugfix

#196 feat: 修改筛选搜索等bug
  components/common/filter/where/index.vue
  components/common/page/Index.vue
  components/common/popup/Index.vue
  components/sale/add/product/Popup.vue
  pages/manage/staffs/staff/list.vue
  pages/sale/deposit/list.vue
  pages/sale/other/list.vue
  pages/sale/sales/list.vue
  pages/sale/service/list.vue
  pages/system/region/list.vue
  pages/system/store/list.vue
  types/repair.d.ts
Labels: enhancement

#193 feat: 新增导出excel方法
  pages/product/accessorie/allocate/info.vue
  pages/product/accessorie/enter/info.vue
  pages/product/accessorie/info.vue
  pages/product/accessorie/record/index.vue
  pages/product/allocate/info.vue
  pages/product/check/info.vue
  pages/product/history/list.vue
  pages/product/manage/finished/info.vue
  pages/product/manage/loss/info.vue
  pages/product/manage/old/info.vue
  pages/product/warehouse/info.vue
  public/excel/finishedTemplate.xlsx
  stores/accessorieRecord.ts
  stores/allocate.ts
  stores/finishedEnter.ts
  types/allocate.d.ts
  types/product.d.ts
  utils/exportXlsx.ts
Labels: enhancement

#198 feat: 优化调拨详情扫码功能
  components/product/list/Main.vue
  components/product/upload/warehouse.vue
  pages/product/allocate/info.vue
  pages/product/list/finished.vue
  pages/product/warehouse/info.vue
  utils/getTime.ts
  utils/handleFileUpload.ts
Labels: enhancement

#199 feat: 增加区域筛选
  components/product/filter/Filter.vue
  components/region/change.vue
  composables/enmuGoods.ts
  pages/system/store/list.vue
  stores/region.ts
  types/region.d.ts
Labels: enhancement

#200 fix: 添加区域选择校验提示
  pages/system/store/list.vue
Labels: maintenance, bugfix

#202 feat: 增加table loading
  components/common/datatable/Index.vue
  pages/manage/staffs/staff/list.vue
  pages/member/lists/list.vue
  pages/product/list/finished.vue
  pages/sale/deposit/list.vue
  pages/sale/other/list.vue
  pages/sale/sales/list.vue
  pages/sale/sales/statement.vue
  pages/sale/service/list.vue
  pages/system/region/list.vue
  stores/staff.ts
Labels: enhancement

#210 feat: 增加API请求loading控制参数
  utils/fetch.ts
Labels: enhancement

#207 fix: 修改盘点按钮文字
  pages/product/check/info.vue
Labels: bugfix

#211 feat: 优化配件选择逻辑及交互
  pages/product/accessorie/allocate/addproduct.vue
  pages/product/accessorie/enter/addproduct.vue
Labels: enhancement

#209 feat: 修改首页枚举
  composables/useDuration.ts
  pages/index/index.vue
  pages/summary/boss/Index.vue
  stores/home.ts
Labels: enhancement

#208 feat: 修改会员
  components/member/lists/New.vue
  components/sale/add/Member.vue
  pages/member/lists/new.vue
  pages/sale/other/add.vue
  pages/sale/sales/add.vue
  stores/stores.ts
Labels: enhancement

#219 fix: 错误提示时长&隐藏批量盘点
  pages/product/check/info.vue
Labels: bugfix

#220 fix: 产品检索缺少关联门店
  pages/product/list/uploadimg.vue
  pages/product/list/view.vue
  stores/fininshed.ts
Labels: bugfix

#216 fix: 修改了必填会员信息,创建订单时
  components/sale/add/Member.vue
  pages/sale/deposit/add.vue
  pages/sale/other/add.vue
  pages/sale/sales/add.vue
  pages/sale/service/add.vue
Labels: enhancement

#222 fix: 批量盘点抽离
  pages/product/check/info.vue
  pages/product/history/list.vue
  stores/check.ts
  types/check.d.ts
Labels: bugfix

#223 fix: 创建调拨单切换门店问题
  pages/product/allocate/add.vue
Labels: bugfix

#225 fix: 货品历史记录显示货品类型；展示盘点单错误提示；
  pages/product/check/info.vue
  pages/product/history/info.vue
  pages/product/history/list.vue
  pages/product/list/finished.vue
  pages/product/list/old.vue
  pages/product/warehouse/info.vue
  stores/product.ts
  types/accessorieRecord.d.ts
  types/product.d.ts
Labels: bugfix

#227 feat: 盘盈、盘亏数据导出
  composables/headerMap.ts
  pages/product/allocate/info.vue
  pages/product/check/info.vue
  pages/product/history/list.vue
  pages/product/list/finished.vue
  pages/product/warehouse/info.vue
  utils/exportHistoryListToXlsx.ts
  utils/exportXlsx.ts
Labels: enhancement
