Repository hnyjzj/jdy-client, pull requests merged in 2025-08, with the labels that each got.

#230 fix: 修复[新增销售单]旧料不自动计算问题
  components/sale/add/Masterials.vue
  components/sale/add/masterials/Handle.vue
  components/sale/add/masterials/Search.vue
  pages/sale/sales/add.vue
  stores/old.ts
  stores/order.ts
  types/order.d.ts
Labels: enhancement, bugfix

#229 refactor: 配件模块重构
  components/accessorie/enter/base.vue
  components/accessorie/enter/info.vue
  components/accessorie/record/card.vue
  components/accessorie/record/table.vue
  components/accessorie/warehouse/accessorie.vue
  components/accessorie/warehouse/category.vue
  components/accessorie/warehouse/force.vue
  components/print/Board.vue
  components/product/manage/Card.vue
  components/product/manage/info.vue
  components/product/upload/warehouse.vue
  components/sale/add/Parts.vue
  components/sale/add/parts/List.vue
  components/sale/add/parts/Search.vue
  components/sale/order/Detail.vue
  components/sale/order/ReturnGoods.vue
  components/sale/statement/Sales.vue
  pages/product/accessorie/allocate/add.vue
  pages/product/accessorie/allocate/addproduct.vue
  pages/product/accessorie/allocate/index.vue
  pages/product/accessorie/allocate/info.vue
  pages/product/accessorie/category/add.vue
  pages/product/accessorie/category/index.vue
  pages/product/accessorie/enter/addproduct.vue
  pages/product/accessorie/enter/index.vue
  pages/product/accessorie/enter/info.vue
  pages/product/accessorie/info.vue
  pages/product/accessorie/list.vue
  pages/product/accessorie/record/index.vue
  pages/product/accessorie/record/info.vue
  pages/sale/sales/add.vue
  pages/sale/sales/statement.vue
  public/excel/accessAllocateTemplate.xlsx
  public/excel/allocateTemplate.xlsx
  public/excel/assessoryTemplate.xlsx
  public/excel/categoryTemplate.xlsx
  stores/accessorie.ts
  stores/accessorieAllocate.ts
  stores/accessorieCategory.ts
  stores/accessorieEnter.ts
  types/accessorie.d.ts
  types/accessorieAllocate.d.ts
  types/accessorieCategory.d.ts
  types/accessorieEnter.d.ts
  types/order.d.ts
  types/where.d.ts
  utils/handleFileUploadAccessorie.ts
  utils/handleFileUploadCategory.ts
Labels: maintenance

#234 feat: 新增批量打印功能；修改配件打印信息；
  components/print/Board.vue
  pages/sale/sales/order.vue
Labels: enhancement

#226 perf: 高级筛选功能优化，增加筛选缓存
  components/common/filter/where/index.vue
  components/common/tool/List.vue
  components/member/lists/List.vue
  components/product/filter/Filter.vue
  components/product/manage/Bottom.vue
  components/region/Card.vue
  components/sale/order/Detail.vue
  components/sale/other/List.vue
  components/sale/statement/Return.vue
  components/sale/statement/Sales.vue
  components/stores/Card.vue
  composables/useOrderStatus.ts
  pages/manage/staffs/staff/list.vue
  pages/member/lists/list.vue
  pages/product/accessorie/allocate/index.vue
  pages/product/accessorie/enter/index.vue
  pages/product/accessorie/list.vue
  pages/product/accessorie/record/index.vue
  pages/product/allocate/index.vue
  pages/product/check/index.vue
  pages/product/history/info.vue
  pages/product/history/list.vue
  pages/product/list/finished.vue
  pages/product/list/loss.vue
  pages/product/list/old.vue
  pages/product/warehouse/index.vue
  pages/sale/deposit/list.vue
  pages/sale/other/list.vue
  pages/sale/sales/list.vue
  pages/sale/sales/refund.vue
  pages/sale/sales/statement.vue
  pages/sale/service/list.vue
  pages/system/region/list.vue
  pages/system/store/list.vue
  stores/depositOrder.ts
  stores/member.ts
  stores/order.ts
  stores/region.ts
  stores/repair.ts
  stores/stores.ts
  types/accessorieRecord.d.ts
  types/depositOrders.d.ts
  types/expandPage.d.ts
  types/member.d.ts
  types/order.d.ts
  types/otherOder.d.ts
  types/product.d.ts
  types/region.d.ts
  types/repair.d.ts
  types/staff.d.ts
  types/statement.d.ts
  types/stores.d.ts
  utils/returnType.ts
  utils/url.ts
Labels: maintenance

#242 fix: 修复入库 undefind 错误、切换门店弹窗报错
  components/accessorie/warehouse/accessorie.vue
  components/correspond/store.vue
  components/product/manage/info.vue
  components/product/upload/warehouse.vue
  pages/product/accessorie/enter/index.vue
Labels: bugfix

#218 feat: 批量数据更新和条码更新
  components/product/upload/Choose.vue
  components/product/upload/code.vue
  components/product/upload/warehouse.vue
  pages/product/allocate/index.vue
  pages/product/allocate/info.vue
  pages/product/list/finished.vue
  public/excel/codeTemplate.xlsx
  stores/fininshed.ts
  types/finished.d.ts
  utils/handleFileUpload.ts
  utils/handleFileUploadCode.ts
Labels: enhancement

#246 fix: 修改[新增销售单,选择配件的应付金额]
  components/sale/add/Parts.vue
  components/sale/add/parts/List.vue
Labels: bugfix

#248 refactor: 优化调拨产品添加逻辑
  pages/product/allocate/info.vue
  pages/product/history/list.vue
  stores/allocate.ts
  types/allocate.d.ts
Labels: enhancement, maintenance

#249 refactor: 修改[新增销售单]
  components/sale/add/Base.vue
  components/sale/add/Depositorder.vue
  components/sale/add/Masterials.vue
  components/sale/add/Member.vue
  components/sale/add/Parts.vue
  components/sale/add/Product.vue
  components/sale/add/Settlement.vue
  components/sale/add/deposit/model.vue
  components/sale/add/masterials/Handle.vue
  components/sale/add/masterials/List.vue
  components/sale/add/masterials/Search.vue
  components/sale/add/parts/List.vue
  components/sale/add/parts/Search.vue
  components/sale/add/product/Deduction.vue
  components/sale/add/product/List.vue
  components/sale/add/product/Popup.vue
  components/sale/deposit/ProductList.vue
  components/sale/order/Detail.vue
  components/sale/order/ReturnGoods.vue
  pages/sale/deposit/add.vue
  pages/sale/other/add.vue
  pages/sale/sales/add.vue
  pages/sale/service/add.vue
  stores/accessorie.ts
  stores/billingSet.ts
  stores/depositOrder.ts
  stores/old.ts
  stores/order.ts
  stores/phrase.ts
  stores/repair.ts
  types/accessorie.d.ts
  types/depositOrders.d.ts
  types/finished.d.ts
  types/old.d.ts
  types/order.d.ts
  utils/options.ts
Labels: maintenance

#251 feat: 新增[批量打印,配件显示总金额]
  components/print/Board.vue
Labels: enhancement

#256 feat: 新增调拨单导出功能
  components/product/allocate/base.vue
  composables/headerMap.ts
  pages/product/accessorie/allocate/index.vue
  pages/product/accessorie/allocate/info.vue
  pages/product/allocate/index.vue
  stores/accessorieAllocate.ts
  stores/allocate.ts
  types/accessorieAllocate.d.ts
  types/allocate.d.ts
  utils/exportXlsx.ts
  utils/manyExportXlsx.ts
Labels: enhancement

#258 fix: 修改盘点验证人判断错误
  pages/product/check/info.vue
Labels: bugfix
