Repository hnyjzj/jdy-client, pull requests merged in 2025-01, with the labels that each got.

#100 feat: 修改公共布局架构，移除原会员布局
  .vscode/settings.json
  app.vue
  assets/css/main.scss
  components/common/area/Index.vue
  components/common/area/Select.vue
  components/common/button/Rounded.vue
  components/common/dark/Index.vue
  components/common/filter/where/index.vue
  components/common/layout/Card.vue
  components/common/layout/Watermark.vue
  components/common/tabbar/Index.vue
  components/stores/Info.vue
  eslint.config.mjs
  layouts/member.vue
  pages/customer/member/billing.vue
  pages/customer/member/card.vue
  pages/customer/member/clear.vue
  pages/customer/member/equity.vue
  pages/customer/member/level.vue
  pages/index/index.vue
  pages/login/index.vue
  pages/my/user/index.vue
  public/images/banner/jdylogo.png
  stores/stores.ts
  uno.config.ts
Labels: enhancement

#101 feat: 优化登录页提示组件及布局
  components/login/tips.vue
  pages/login/index.vue
Labels: enhancement

#102 feat: 添加鼠标事件及优化信息卡片布局
  components/work/card/Information.vue
  utils/MouseEvent.ts
Labels: enhancement

#99 feat: 添加客户管理相关接口
  components/common/gradient/Index.vue
  components/common/tags/Index.vue
  components/member/customer/Maintain.vue
  components/member/lists/Info.vue
  components/member/lists/Inform.vue
  components/member/lists/List.vue
  components/member/lists/New.vue
  pages/member/lists/info.vue
  pages/member/lists/inform.vue
  pages/member/lists/list.vue
  pages/member/lists/new.vue
  pnpm-lock.yaml
  stores/member.ts
  types/member.d.ts
Labels: enhancement

#107 refactor: 优化成品错误类型定义
  components/product/finished/List.vue
Labels: maintenance

#108 feat: 移除冗余的common-avatar属性
  components/product/manage/Card.vue
  components/stores/Card.vue
Labels: enhancement

#103 feat!: 添加 TS 类型检查及类型优化
  .github/workflows/check.yml
  components/login/info.vue
  components/member/customer/Maintain.vue
  components/member/integral/Record.vue
  components/product/finished/List.vue
  components/product/manage/Card.vue
  components/product/manage/Fold.vue
  components/sale/sales/Grades.vue
  components/staff/mamage/Add.vue
  components/stores/AddUpdate.vue
  components/stores/Card.vue
  nuxt.config.ts
  package.json
  pages/member/customer/maintain.vue
  pages/member/integral/record.vue
  pages/sale/search/member.vue
  pnpm-lock.yaml
Labels: enhancement, break

#104 feat: 优化工作台栏目
  components/product/filter/Filter.vue
  components/product/manage/Company.vue
  components/work/Bench.vue
  pages/product/manage/list.vue
Labels: enhancement

#111 refactor: 调整列表下拉组件
  app.vue
  components/common/gradient/Index.vue
  components/member/lists/List.vue
  pages/member/lists/list.vue
Labels: maintenance

#110 fix: 图标不显示和工作台编辑状态禁止跳转
  components/product/manage/Company.vue
  components/work/Bench.vue
  pages/product/manage/list.vue
Labels: bugfix

#109 feat: 合并员工新增逻辑并优化界面布局
  pages/manage/staffs/staff/add.vue
  pages/staff/list/add.vue
  pages/staff/list/index.vue
Labels: enhancement

#117 feat: 添加图标配置及优化工作流
  .github/workflows/check.yml
  .vscode/settings.json
  iconify.config.json
  nuxt.config.ts
  package.json
  pnpm-lock.yaml
  tsconfig.json
Labels: enhancement

#119 feat: 添加图标配置及优化工作流 (#117)
  .github/workflows/check.yml
  .vscode/settings.json
  iconify.config.json
  nuxt.config.ts
  package.json
  pnpm-lock.yaml
  tsconfig.json
Labels: enhancement

#115 feat: 新增编辑用户接口，调整new页面
  components/common/gradient/Index.vue
  components/common/model/Index.vue
  components/member/lists/Info.vue
  components/member/lists/List.vue
  components/sale/add/Settlement.vue
  components/work/card/Action.vue
  error.vue
  pages/index/index.vue
  pages/member/lists/info.vue
  pages/member/lists/list.vue
  pages/member/lists/new.vue
  types/member.d.ts
  types/todo.d.ts
Labels: enhancement

#114 feat: 修改门店管理，增加门店详情中的员工展示
  .env.example
  components/common/dark/Index.vue
  components/common/tabbar/Index.vue
  components/staff/manage/Add.vue
  components/stores/Card.vue
  components/stores/Info.vue
  components/work/card/Digitalization.vue
  pages/index/index.vue
  types/stores.d.ts
Labels: enhancement
