Repository hnyjzj/jdy-client, pull requests merged in 2025-02, with the labels that each got.

#121 feat: 修改样式问题以及添加了一个门店搜索框
  components/common/fold/Index.vue
  components/common/list/Pull.vue
  components/common/tags/Index.vue
  components/product/filter/Search.vue
  components/product/filter/Senior.vue
  components/product/manage/Company.vue
  components/sale/Cards.vue
  components/staff/manage/Add.vue
  components/staff/manage/Card.vue
  components/work/Bench.vue
  pages/manage/staffs/staff/add.vue
  pages/manage/staffs/staff/list.vue
  pages/my/user/information.vue
  stores/stores.ts
  types/staff.d.ts
Labels: enhancement

#112 feat: 入库单列表
  components/product/manage/Card.vue
  pages/product/finished/warehouse.vue
  pages/product/finished/warehouse/add.vue
  pages/product/finished/warehouse/index.vue
  pages/product/finished/warehouse/info.vue
  pages/work/table/index.vue
  stores/enter.ts
  types/enter..d.ts
Labels: enhancement

#116 feat: 新增调拨管理模块
  app.vue
  components/common/button/One.vue
  components/common/filter/where/index.vue
  components/common/popup/Index.vue
  components/product/finished/List.vue
  components/product/manage/Company.vue
  components/work/Bench.vue
  pages/product/goods/allocate/add.vue
  pages/product/goods/allocate/index.vue
  pages/product/goods/allocate/info.vue
  pages/product/goods/transfer/add.vue
  pages/product/goods/transfer/index.vue
  pages/product/manage/list.vue
  pages/work/table/index.vue
  stores/allocate.ts
  types/allocate.d.ts
  types/product.d.ts
  types/where.d.ts
  types/work_table.d.ts
  utils/getTime.ts
Labels: enhancement

#125 feat: 优化Nitro配置以替换浏览器检测
  app.vue
  nuxt.config.ts
Labels: enhancement, maintenance

#124 feat: 增加登录方式标题及工作台搜索
  assets/icons/search-close.svg
  components/login/Other.vue
  components/login/info.vue
  components/product/filter/Search.vue
  components/product/manage/Company.vue
  components/staff/manage/Card.vue
  components/work/Bench.vue
  pages/login/index.vue
  pages/my/user/information.vue
  pages/work/table/index.vue
  stores/workbenche.ts
  types/work_table.d.ts
  utils/filterByKeyword.ts
Labels: enhancement

#122 feat: 添加会员积分相关功能
  components/common/button/Bottom.vue
  components/common/toast/Index.vue
  components/member/integral/Record.vue
  components/member/lists/Info.vue
  components/member/lists/List.vue
  pages/member/integral/record.vue
  pages/member/lists/info.vue
  pages/member/lists/list.vue
  stores/member.ts
  types/member.d.ts
Labels: enhancement

#123 feat: 新增黄金价格管理功能
  pages/system/gold/price.vue
  stores/gold.ts
  types/gold.d.ts
Labels: enhancement

#127 fix: 修复首页表格样式问题
  components/work/card/Digitalization.vue
Labels: bugfix

#126 feat: 优化销售单列表及筛选功能 (#126)
  app.vue
  components/common/cell/index.vue
  components/common/filter/where/index.vue
  components/common/list/Pull.vue
  components/common/popup/Index.vue
  components/common/tags/Index.vue
  components/product/filter/Filter.vue
  components/product/filter/Search.vue
  components/sale/Cards.vue
  components/sale/add/Base.vue
  components/sale/add/Product.vue
  components/sale/order/Detail.vue
  components/sale/sales/List.vue
  components/work/card/Information.vue
  pages/member/lists/new.vue
  pages/sale/sales/add.vue
  pages/sale/sales/list.vue
  pages/sale/sales/order.vue
  pages/sale/search/member.vue
  pages/work/table/index.vue
  stores/order.ts
  stores/staff.ts
  stores/stores.ts
  types/member.d.ts
  types/order.d.ts
  types/response.d.ts
  utils/url.ts
Labels: enhancement

#129 feat: 优化销售单表单布局及样式
  components/common/button/Rounded.vue
  components/common/filter/where/index.vue
  components/product/filter/Filter.vue
  components/product/manage/Company.vue
  components/sale/add/Base.vue
  components/sale/add/Product.vue
  components/sale/add/Settlement.vue
  components/sale/order/Detail.vue
  components/sale/sales/List.vue
  components/staff/manage/Add.vue
  pages/index/index.vue
  pages/manage/staffs/staff/add.vue
  pages/sale/sales/add.vue
  pages/sale/sales/list.vue
  pages/sale/sales/order.vue
  types/order.d.ts
  types/response.d.ts
Labels: enhancement

#132 fix: 修正404页面在移动端显示错位的问题
  app.vue
  components/common/model/Index.vue
  components/member/integral/Record.vue
  components/product/filter/Filter.vue
  error.vue
Labels: maintenance, bugfix

#130 feat: 优化商品搜索及模态框样式
  components/sale/add/Product.vue
  components/sale/sales/List.vue
  pages/sale/sales/add.vue
  pages/sale/sales/list.vue
  utils/options.ts
Labels: enhancement

#128 feat: 新增旧料列表和报损列表
  app.vue
  assets/icons/download.svg
  components/common/filter/where/index.vue
  components/common/gradient/Index.vue
  components/common/list/Pull.vue
  components/common/tab/Secondary.vue
  components/product/filter/Filter.vue
  components/product/finished/List.vue
  components/product/manage/Bottom.vue
  components/product/upload/warehouse.vue
  pages/product/accessory/allocate.vue
  pages/product/accessory/stock.vue
  pages/product/accessory/warehouse.vue
  pages/product/finished/allocate/add.vue
  pages/product/finished/allocate/index.vue
  pages/product/finished/allocate/info.vue
  pages/product/finished/check/add.vue
  pages/product/finished/check/index.vue
  pages/product/finished/check/info.vue
  pages/product/finished/edit.vue
  pages/product/finished/info.vue
  pages/product/finished/list.vue
  pages/product/finished/stocktaking.vue
  pages/product/finished/warehouse/add.vue
  pages/product/finished/warehouse/index.vue
  pages/product/finished/warehouse/info.vue
  pages/product/goods/check/add.vue
  pages/product/goods/check/index.vue
  pages/product/loss/list.vue
  pages/product/manage/goods.vue
  pages/product/manage/list.vue
  pages/product/manage/record/index.vue
  pages/product/manage/update/index.vue
  pages/product/old/list.vue
  pages/system/gold/price.vue
  public/excel/assessoryTemplate.xlsx
  public/excel/finishedTemplate.xlsx
  stores/check.ts
  stores/product.ts
  types/check.d.ts
  types/product.d.ts
  types/where.d.ts
  utils/getTime.ts
  utils/handleFileUpload.ts
Labels: enhancement

#136 feat: 修改订单列表为分页
  components/common/page/Index.vue
  components/sale/add/Base.vue
  nuxt.config.ts
  package.json
  pages/sale/sales/list.vue
  pages/work/table/index.vue
  pnpm-lock.yaml
  stores/order.ts
Labels: enhancement

#133 feat: 新增首页数据存储及优化界面显示
  components/home/Action.vue
  components/home/Store.vue
  components/home/greet.vue
  components/sale/add/Product.vue
  components/summary/card/Boss.vue
  components/summary/card/Inventory.vue
  components/summary/card/Sale.vue
  pages/index/index.vue
  pages/summary/boss/Index.vue
  stores/home.ts
  types/home.d.ts
Labels: enhancement

#137 chore: 优化组件表现样式
  components/common/button/Bottom.vue
  components/common/empty/Index.vue
  components/member/integral/Record.vue
  components/member/lists/Info.vue
  components/member/lists/List.vue
  components/product/filter/Filter.vue
  pages/finance/achievement/rule.vue
  pages/member/integral/record.vue
  pages/member/lists/list.vue
  pages/member/lists/new.vue
  pages/sale/deposit/info.vue
  pages/sale/other/info.vue
  pages/sale/repair/info.vue
  pages/sale/search/member.vue
  pages/sale/search/product.vue
  stores/member.ts
Labels: maintenance
