Repository hnyjzj/jdy-client, pull requests merged in 2025-09, with the labels that each got.

#262 feat: 货品图片展示
  components/common/avatar/Index.vue
  components/product/manage/info.vue
  components/sale/order/Detail.vue
  pages/product/history/list.vue
  types/old.d.ts
Labels: enhancement

#261 fix: 修复定金单跳转和抵扣金额显示问题
  components/sale/add/Masterials.vue
  components/sale/add/Settlement.vue
  components/sale/add/masterials/Search.vue
  components/sale/deposit/List.vue
  pages/sale/sales/add.vue
Labels: bugfix

#263 fix: 处理打印报表时的错误处理和空数据情况
  components/print/Statement.vue
  pages/summary/sales_detail.vue
  stores/statement.ts
Labels: bugfix

#253 feat!: 新增Boos看板
  assets/css/main.scss
  assets/icons/chart-boss.svg
  assets/icons/table-boss.svg
  components/common/filter/where/index.vue
  components/member/lists/New.vue
  components/summary/Table.vue
  components/summary/boss/Card.vue
  components/summary/boss/SelectTime.vue
  components/summary/card/Boss.vue
  components/summary/card/Inventory.vue
  components/summary/card/Sale.vue
  components/summary/stock/Table.vue
  nuxt.config.ts
  pages/index/index.vue
  pages/member/lists/edit.vue
  pages/member/lists/editwx.vue
  pages/summary/boss/Index.vue
  pages/summary/boss/index.vue
  pages/summary/revenue.vue
  pages/summary/sales_detail.vue
  pages/summary/stock/index.vue
  stores/boss.ts
  stores/home.ts
  stores/stock.ts
  types/stock.d.ts
  utils/getTime.ts
Labels: enhancement, break

#266 style: 调整浅色模式下表格单元格背景色为#D9E4F4
  components/summary/Table.vue
Labels: maintenance

#271 fix: 优化盘点单详情获取和错误处理
  pages/product/check/info.vue
  stores/check.ts
Labels: bugfix

#273 style: 优化收支统计的门店选择和时间选择组件样式与功能
  components/product/manage/Company.vue
  components/summary/boss/SelectTime.vue
  pages/summary/cashflow/index.vue
Labels: enhancement

#280 fix: 修改打印配件金额不正确
  components/print/Board.vue
Labels: bugfix

#281 feat: 调拨出库增加选择总部
  pages/product/accessorie/allocate/add.vue
  pages/product/accessorie/allocate/index.vue
  pages/product/allocate/add.vue
  pages/product/allocate/index.vue
  stores/stores.ts
  types/accessorieAllocate.d.ts
  types/allocate.d.ts
Labels: enhancement

#284 feat: 新增调拨单门店显示为别名
  components/product/allocate/base.vue
  components/product/manage/Company.vue
  pages/product/accessorie/allocate/add.vue
  pages/product/accessorie/allocate/info.vue
  pages/product/accessorie/record/index.vue
  pages/product/allocate/add.vue
  pages/product/check/add.vue
  pages/product/check/index.vue
  pages/product/history/list.vue
  pages/product/warehouse/add.vue
  stores/stores.ts
Labels: enhancement

#283 feat: 新增区域门店列表的别名
  .vscode/settings.json
  components/common/gradient/Index.vue
  components/product/allocate/base.vue
  components/product/manage/Company.vue
  components/region/AddUpdate.vue
  components/region/AssignStaff.vue
  components/region/AssignSuper.vue
  components/region/Assignstore.vue
  components/region/Card.vue
  components/region/Info.vue
  components/stores/AddUpdate.vue
  components/stores/Card.vue
  components/stores/Info.vue
  pages/product/accessorie/allocate/add.vue
  pages/product/accessorie/allocate/info.vue
  pages/product/accessorie/record/index.vue
  pages/product/allocate/add.vue
  pages/product/check/add.vue
  pages/product/check/index.vue
  pages/product/history/list.vue
  pages/product/warehouse/add.vue
  pages/system/region/info.vue
  pages/system/region/list.vue
  pages/system/store/info.vue
  pages/system/store/list.vue
  stores/stores.ts
  types/region.d.ts
  types/stores.d.ts
Labels: enhancement

#286 fix: 添加计件商品价格校验逻辑
  components/sale/add/Product.vue
  pages/sale/sales/add.vue
Labels: bugfix

#287 feat: 添加门店和区域管理员功能
  components/print/Board.vue
  components/region/AssignStaff.vue
  components/region/AssignSuper.vue
  components/region/Card.vue
  components/sale/service/info/Index.vue
  components/staff/assign/Card.vue
  components/staff/assign/StaffCard.vue
  components/staff/assign/Superior.vue
  components/staff/manage/Card.vue
  components/staff/manage/Display.vue
  components/staff/manage/Stores.vue
  components/stores/AddUpdate.vue
  components/stores/AssignStaff.vue
  components/stores/Card.vue
  components/stores/Info.vue
  pages/manage/staffs/staff/edit.vue
  pages/manage/staffs/staff/info.vue
  pages/manage/staffs/staff/list.vue
  pages/system/region/info.vue
  pages/system/region/list.vue
  pages/system/store/info.vue
  pages/system/store/list.vue
  pages/system/store/notice.vue
  stores/region.ts
  stores/stores.ts
  types/region.d.ts
  types/staff.d.ts
  types/stores.d.ts
Labels: enhancement

#288 docs: 将"负责人"修改为"管理员"
  components/region/Card.vue
Labels: documentation

#289 feat: 为不同订单类型添加状态颜色映射并优化标签显示
  components/common/tags/Index.vue
  components/sale/Cards.vue
  components/sale/deposit/List.vue
  components/sale/sales/List.vue
  components/sale/service/list/Index.vue
  components/sale/statement/Sales.vue
  composables/useOrderStatus.ts
Labels: enhancement

#294 feat: 截屏提醒时添加页面标题
  app.vue
Labels: enhancement

#297 feat: 调拨单门店显示改为别名
  components/product/allocate/AccessPrintInfo.vue
  components/product/allocate/Printinfo.vue
  components/product/allocate/base.vue
  pages/product/accessorie/allocate/index.vue
  pages/product/accessorie/allocate/info.vue
  pages/product/allocate/index.vue
  pages/product/allocate/info.vue
  utils/exportXlsx.ts
  utils/manyExportXlsx.ts
Labels: enhancement

#298 feat: 添加Excel导出数据格式化功能
  utils/exportHistoryListToXlsx.ts
  utils/exportStatementXls.ts
  utils/exportXlsx.ts
  utils/formatFloatFieldsInWorksheet.ts
  utils/manyExportXlsx.ts
Labels: enhancement

#300 feat: 添加合计行折线图并调整y轴配置
  components/summary/Table.vue
  pages/summary/boss/index.vue
  pages/summary/sale/index.vue
  stores/boss.ts
  utils/objectSort.ts
Labels: enhancement

#302 fix: 修改销售单打印
  components/print/Board.vue
  components/sale/order/Detail.vue
  pages/sale/sales/order.vue
Labels: bugfix

#303 feat: 优化个人销售统计排序和新增销售报表表格滑动
  components/summary/stock/Table.vue
  pages/summary/sale/index.vue
  stores/stock.ts
  utils/objectSort.ts
Labels: enhancement
