Repository hnyjzj/jdy-client, pull requests merged in 2025-03, with the labels that each got.

#131 feat: 新增分配员工页面
  app.vue
  components/staff/assign/Card.vue
  components/staff/manage/Add.vue
  components/stores/AddUpdate.vue
  components/stores/Assign.vue
  components/stores/Info.vue
  pages/manage/staffs/staff/add.vue
  pages/system/store/assign.vue
  pages/system/store/info.vue
  pages/system/store/list.vue
  stores/staff.ts
  stores/stores.ts
  types/stores.d.ts
Labels: enhancement

#138 chore: 完善弹窗初始化方法
  components/common/gradient/Index.vue
  components/common/page/Index.vue
  pages/member/integral/record.vue
  pages/member/lists/list.vue
  stores/member.ts
Labels: maintenance

#140 fix: 修正积分页和列表页searchPage未分离的问题, 并添加数据为空时的展示样式
  components/member/integral/Record.vue
  components/member/lists/List.vue
  pages/member/integral/record.vue
  pages/member/lists/list.vue
  stores/member.ts
Labels: bugfix

#141 feat: 金价管理
  components/common/button/Bottom.vue
  components/common/button/One.vue
  components/common/model/Index.vue
  pages/system/gold/price.vue
  stores/gold.ts
  types/gold.d.ts
  types/product.d.ts
Labels: enhancement

#142 feat: 新增金价跳转及优化员工列表分页
  components/summary/card/Sale.vue
  pages/manage/staffs/staff/list.vue
  pages/system/store/info.vue
  stores/staff.ts
Labels: enhancement

#144 feat: 修改bug以及新增了二次确认弹窗
  components/common/confirm/Index.vue
  components/home/Action.vue
  pages/manage/staffs/staff/add.vue
  pages/manage/staffs/staff/list.vue
  pages/system/store/info.vue
  pages/system/store/list.vue
Labels: enhancement, maintenance

#146 feat: 优化响应数据空值处理及登录重定向逻辑
  pages/login/index.vue
  pages/login/oauth.vue
  pages/manage/staffs/staff/add.vue
  pages/member/lists/new.vue
  pages/my/user/information.vue
  pages/my/user/oauth.vue
  pages/product/accessory/allocate.vue
  pages/product/accessory/stock.vue
  pages/product/finished/allocate/add.vue
  pages/product/finished/allocate/index.vue
  pages/product/finished/allocate/info.vue
  pages/product/finished/check/add.vue
  pages/product/finished/check/index.vue
  pages/product/finished/check/info.vue
  pages/product/finished/edit.vue
  pages/product/finished/info.vue
  pages/product/finished/list.vue
  pages/product/finished/warehouse/add.vue
  pages/product/finished/warehouse/index.vue
  pages/product/loss/list.vue
  pages/product/old/list.vue
  pages/sale/sales/add.vue
  pages/system/gold/price.vue
  pages/system/store/list.vue
  pages/work/table/index.vue
  stores/allocate.ts
  stores/auth.ts
  stores/check.ts
  stores/enter.ts
  stores/home.ts
  stores/member.ts
  stores/order.ts
  stores/product.ts
  stores/staff.ts
  stores/stores.ts
  stores/wxwork.ts
  utils/fetch.ts
Labels: enhancement

#147 feat: 新增登录加载页及优化重定向逻辑
  middleware/auth.global.ts
  pages/login/index.vue
  pages/login/loading.vue
  pages/login/oauth.vue
  stores/auth.ts
  stores/wxwork.ts
  utils/fetch.ts
Labels: enhancement, maintenance
